import Body from "@/components/Body";
import { Stack } from "@chakra-ui/react";
import { Inter } from "next/font/google";
import Navbar from "../components/Navbar/Navbar";
//import { chakra } from '@chakra-ui/react'
const inter = Inter({ subsets: ["latin"] });
import { Providers } from "./providers";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <Navbar />
                    <Body>{children}</Body>
                </Providers>
            </body>
        </html>
    );
}
