name: Workflow for Codecov example-javascript
on:
    push:
        branches: [main, m3-dev, tests]
        paths-ignore:
            - "*.md"

    pull_request:
        branches: [main, m3-dev]
        paths-ignore:
            - "*.md"
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm install
            - name: "Create env file"
              run: echo "${{ secrets.ENV_FILE }}" > .env
            - name: Run tests and collect coverage
              run: npm run test
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
